version: '3.8'
services:
  passive-recon-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passive-recon-api
    volumes:
      -  /mnt/.docker/recon/:/data
    environment:
      - VIRTUAL_HOST=recon.wolfznet.uk
      - LETSENCRYPT_HOST=recon.wolfznet.uk
      - LETSENCRYPT_EMAIL=muhammed.m.abdelkader@gmail.com
    networks:
      - shared-net
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  shared-net:
    external: true
